interface Products{
    sys:{
      id:string
    }
    fields:{
      title:string,
      price:string,
      description:string,
      slug:string,
      image:{
        fields:{
          file:{
            url:string
          }
        }
      }[],
      size:string[]
    }
  }[]